name: Proposition n°1 - Bug Report
description: Report an issue in module. DO NOT disclose security issues here, contact security@prestashop.com instead!
type: 'Bug'
body:
  - type: markdown
    attributes:
      value: |
        ###️ Read this before submitting your bug report:
        - **Write in English.** Reports in all other languages will be closed.
        - **Provide as much detail as possible** - error logs, screenshots, your exact configuration. If the issue cannot be reproduced, it cannot be fixed.
        - **Follow the [bug report guidelines](https://devdocs.prestashop-project.org/9/contribute/contribute-reporting-issues/#best-practices-for-writing-an-issue).** This will help issue managers qualify your report faster.
        - As explained [in this page](https://www.prestashop-project.org/security/sharing-third-party-distributions/), the team behind the project only maintains distribution under the official PrestaShop or PrestaShopCorp GitHub organizations. Please mention how you installed PrestaShop. If you used a third-party distribution and experience issues not reproducible with the official version, we might redirect you to that distribution's maintainers.
        - **Avoid reporting "error 500" or "white page" errors** - this is a universal error message that does not provide enough information to qualify the issue. Enable debug mode in the Performance section of PrestaShop or manually in `/config/defines.inc.php` and try again. You should get a proper error message.
  - type: checkboxes
    attributes:
      label: Prerequisites
      options:
        - label: I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
          required: true
        - label: I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.
          required: true
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Resume the bug
  - type: textarea
    id: preconditions
    attributes:
      label: Preconditions
      description: |
        List the exact preconditions to be able to reproduce the bug like build a fresh new shop, modules versions, which feature is activated or not, if a .csv of products need to be imported, location (like country(ies), currency(ies)..) : any information that could be relevant.
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: List the exact steps to reproduce the issue.
      placeholder: |
        1. Go to ‘…’
        2. Click on ‘…’
        3. Scroll down to ‘…’
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: Explain the right behaviour expected for each steps.
      placeholder: |
        1. Page is displayed
        2. Modal ‘…’ is displayed
        3. ‘…’ is displayed
    validations:
      required: true
  - type: textarea
    id: actual-results
    attributes:
      label: Actual results/bug and add attachments
      description: What went wrong ? If possible, add screenshots, error logs or screen recordings to help explain your problem.
      placeholder: |
        1. Page is displayed
        2. Modal ‘…’ is displayed
        3. ‘…’ is not displayed**
        **Screenshots :**
    validations:
      required: true
  - type: textarea
    id: remark
    attributes:
      label: Remark(s)
      description: Add additional remarks if needed
  - type: input
    id: prestashop-version
    attributes:
      label: PrestaShop version(s) where the bug happened
      description: Specify which versions your issue come from
      placeholder: "e.g., from 1.7.5.2 or 1.7.8.0"
    validations:
      required: true
  - type: input
    id: installed-prestashop
    attributes:
      label: How you installed PrestaShop
      description: Choose the method you used to install PrestaShop.
      placeholder: "e.g., downloading the package and where you downloaded it, using git clone, the docker image…"
  - type: input
    id: php-version
    attributes:
      label: PHP version(s) where the bug happened
      placeholder: "e.g., 7.1 or 8.0"
  - type: input
    id: sponsor-company
    attributes:
      label: Your company or customer's name goes here (if applicable).
